//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnseremDbEntities : DbContext
    {
        public AnseremDbEntities()
            : base("name=AnseremDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sales> Sales { get; set; }
        public DbSet<Сities> Сities { get; set; }
        public DbSet<Сontacts> Сontacts { get; set; }
        public DbSet<Сounterpartys> Сounterpartys { get; set; }
    }
}
