//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleId { get; set; }
        public string SaleName { get; set; }
        public int СounterpartyId { get; set; }
        public int ContactId { get; set; }
        public int CityId { get; set; }
    
        public virtual Сities Сities { get; set; }
        public virtual Сontacts Сontacts { get; set; }
        public virtual Сounterpartys Сounterpartys { get; set; }
    }
}
