//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сontacts
    {
        public Сontacts()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int ContactId { get; set; }
        public string CounterpartyContact { get; set; }
        public string SalerContact { get; set; }
    
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
